spring.application.name=MedBackEnd
# Caminho para o arquivo de credenciais do Firebase (ajuste conforme a localização real)
firebase.credentials.path=src/main/resources/firebase/serviceAccountKey.json
