# PostgreSQL (Docker mapeado em 5432 -> 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/projeto_integrador
spring.datasource.username=postgres
spring.datasource.password=postgres
# driver-class-name é opcional no Boot 3, mas pode deixar
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080

# Logging (opcional)
logging.level.br.pucgo.ads.projetointegrador=DEBUG
logging.level.org.springframework.web=DEBUG

# ==== JWT ====
security.jwt.secret=CHANGEME-SUPER-SECRET-KEY-32-CHARS-MIN
security.jwt.issuer=pi-eldercare
security.jwt.expiration=3600000   # 1h (em milissegundos)
